version: "3"
services:
    docker_centos_myserver:
        build:
            context: .
            args:
                PHP_VERSION: ${PHP_VERSION}
        volumes:  
            - ./web:/web:rw
            - ./tool:/tool:rw
            - ${CONF}/nginx/conf:/usr/local/nginx/conf:rw
            - ${CONF}/nginx/vhosts:/usr/local/nginx/vhosts:rw
            - ${CONF}/nginx/logs:/usr/local/nginx/logs:rw
            - ${CONF}/php_fpm/:/usr/local/php/${PHP_VERSION}/etc/:rw
            - ${CONF}/php/:/etc/php/${PHP_VERSION}/cli/:rw
        ports:
            - "9501:9501"
            - "80:80"
        depends_on:
            -  mysql  #依赖mysql
        command: /bin/bash -c 'sh /tool/sh/sh.sh;run' #开机启动
        #entrypoint: ["/usr/sbin/init"] #加了这句command无效，entrypoint可以让centos放开更多功能,例如设置开机启动等
        restart: always     #失败重启
        tty: true      #不退出容器
        privileged: true  #加权
    mysql:
        image: mysql:${MYSQL_VERSION}
        volumes:
            - ./mysql/data:/var/lib/mysql:rw
            - ./mysql/conf:/etc/mysql:rw
        privileged: true     #加权     
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            # MYSQL_ROOT_PASSWORD ： root用户的密码，这里设置的初始化密码为`123456`；
            # MYSQL_DATABASE ： 运行时需要创建的数据库名称；
            # MYSQL_USER ： 运行时需要创建用户名，与MYSQL_PASSWORD一起使用；
            # MYSQL_PASSWORD ： 运行时需要创建的用户名对应的密码，与MYSQL_USER一起使用；
            # MYSQL_ALLOW_EMPTY_PASSWORD ： 是否允许root用户的密码为空，该参数对应的值为:yes；
            # MYSQL_RANDOM_ROOT_PASSWORD：为root用户生成随机密码；
            # MYSQL_ONETIME_PASSWORD ： 设置root用户的密码必须在第一次登陆时修改（只对5.6以上的版本支持）。
            # MYSQL_ROOT_PASSWORD 和 MYSQL_RANDOM_ROOT_PASSWORD 两者必须有且只有一个

 
 
         
